# permissions for end users to view testks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testk-viewer-role
rules:
- apiGroups:
  - zmzapp.zmz.example.org
  resources:
  - testks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zmzapp.zmz.example.org
  resources:
  - testks/status
  verbs:
  - get
