# permissions for end users to edit testks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testk-editor-role
rules:
- apiGroups:
  - zmzapp.zmz.example.org
  resources:
  - testks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zmzapp.zmz.example.org
  resources:
  - testks/status
  verbs:
  - get
