apiVersion: v1
kind: Namespace
metadata:
  name: testk-test
---
apiVersion: zmzapp.zmz.example.org/v1
kind: TestK
metadata:
  name: testk-sample
  namespace: testk-test
spec:
  # Add fields here
  foo: bar
  deploySpec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
